<script>
	let moles = Array(9).fill(false); // 9 positions for moles
	let score = 0;
	let gameActive = false;
	let clickedWord = ''; // Variable to hold the word of the clicked mole
	let showXEmoji = false; // Variable to control the display of the X emoji
	let showCheckEmoji = false; // Variable to control the display of the check emoji
	let clickedWordList = []; // Array to hold the list of clicked words
	const words = [
		'Definition',
		'Example',
		'Translation',
		'Synonym',
		'Antonym',
		'a',
		'able',
		'about',
		'above',
		'across',
		'act',
		'action',
		'actually',
		'add',
		'addition',
		'adjective',
		'afraid',
		'Africa',
		'after',
		'again',
		'against',
		'age',
		'ago',
		'agreed',
		'ahead',
		'air',
		'all',
		'allow',
		'almost',
		'alone',
		'along',
		'already',
		'also',
		'although',
		'always',
		'am',
		'America',
		'among',
		'amount',
		'an',
		'and',
		'angle',
		'animal',
		'another',
		'answer',
		'any',
		'anything',
		'appear',
		'apple',
		'are',
		'area',
		'arms',
		'army',
		'around',
		'arrived',
		'art',
		'as',
		'ask',
		'at',
		'away',
		'baby',
		'back',
		'bad',
		'ball',
		'bank',
		'base',
		'be',
		'bear',
		'beat',
		'beautiful',
		'became',
		'because',
		'become',
		'bed',
		'been',
		'before',
		'began',
		'begin',
		'behind',
		'being',
		'believe',
		'bell',
		'belong',
		'below',
		'beside',
		'best',
		'better',
		'between',
		'big',
		'bill',
		'birds',
		'bit',
		'black',
		'block',
		'blood',
		'blow',
		'blue',
		'board',
		'boat',
		'body',
		'bones',
		'book',
		'born',
		'both',
		'bottom',
		'bought',
		'box',
		'boy',
		'branches',
		'break',
		'bright',
		'bring',
		'British',
		'broken',
		'brother',
		'brought',
		'brown',
		'build',
		'building',
		'built',
		'burning',
		'business',
		'but',
		'buy',
		'by',
		'called',
		'came',
		'can',
		'cannot',
		'can’t',
		'capital',
		'captain',
		'car',
		'care',
		'carefully',
		'carry',
		'case',
		'cat',
		'catch',
		'cattle',
		'caught',
		'cause',
		'cells',
		'center',
		'cents',
		'century',
		'certain',
		'chance',
		'change',
		'chart',
		'check',
		'chief',
		'child',
		'children',
		'choose',
		'church',
		'circle',
		'city',
		'class',
		'clean',
		'clear',
		'climbed',
		'close',
		'clothes',
		'cloud',
		'coast',
		'cold',
		'color',
		'column',
		'come',
		'common',
		'company',
		'compare',
		'complete',
		'compound',
		'conditions',
		'consider',
		'consonant',
		'contain',
		'continued',
		'control',
		'cook',
		'cool',
		'copy',
		'corn',
		'corner',
		'correct',
		'cost',
		'cotton',
		'could',
		'couldn’t',
		'count',
		'country',
		'course',
		'covered',
		'cows',
		'create',
		'cried',
		'crops',
		'cross',
		'crowd',
		'current',
		'cut',
		'dance',
		'dark',
		'day',
		'dead',
		'deal',
		'death',
		'decided',
		'decimal',
		'deep',
		'describe',
		'desert',
		'design',
		'had',
		'hair',
		'half',
		'hand',
		'happened',
		'happy',
		'hard',
		'has',
		'hat',
		'have',
		'he',
		'head',
		'hear',
		'heard',
		'heart',
		'heat',
		'heavy',
		'held',
		'help',
		'her',
		'here',
		'high',
		'hill',
		'him',
		'himself',
		'his',
		'history',
		'hit',
		'hoe',
		'hold',
		'hole',
		'home',
		'hope',
		'horse',
		'hot',
		'hours',
		'house',
		'how',
		'however',
		'huge',
		'human',
		'hundred',
		'hunting',
		'I',
		'ice',
		'idea',
		'if',
		'I’ll',
		'important',
		'in',
		'inches',
		'include',
		'increase',
		'Indian',
		'indicate',
		'industry',
		'information',
		'insects',
		'inside',
		'instead',
		'instruments',
		'interest',
		'interesting',
		'into',
		'iron',
		'is',
		'island',
		'isn’t',
		'it',
		'it’s',
		'itself',
		'Japanese',
		'job',
		'joined',
		'jumped',
		'just',
		'keep',
		'kept',
		'key',
		'killed',
		'kind',
		'king',
		'knew',
		'know',
		'known',
		'lady',
		'lake',
		'land',
		'language',
		'large',
		'last',
		'late',
		'laughed',
		'law',
		'lay',
		'lead',
		'learn',
		'least',
		'leave',
		'led',
		'left',
		'legs',
		'length',
		'less',
		'let',
		'let’s',
		'letter',
		'level',
		'lie',
		'life',
		'lifted',
		'light',
		'like',
		'line',
		'list',
		'listen',
		'little',
		'live',
		'located',
		'long',
		'look',
		'lost',
		'lot',
		'loud',
		'love',
		'low',
		'machine',
		'made',
		'main',
		'major',
		'make',
		'mall',
		'man',
		'many',
		'map',
		'march',
		'mark',
		'match',
		'material',
		'matter',
		'may',
		'maybe',
		'me',
		'means',
		'measure',
		'meat',
		'meet',
		'melody',
		'members',
		'men',
		'metal',
		'method',
		'middle',
		'might',
		'mile',
		'milk',
		'million',
		'mind',
		'mine',
		'minutes',
		'miss',
		'modern',
		'molecules',
		'moment',
		'money',
		'months',
		'moon',
		'more',
		'morning',
		'most',
		'mother',
		'mountains',
		'mouth',
		'move',
		'movement',
		'much',
		'music',
		'must',
		'my',
		'name',
		'nation',
		'natural',
		'near',
		'necessary',
		'need',
		'never',
		'new',
		'next',
		'night',
		'no',
		'north',
		'northern',
		'nose',
		'not',
		'note',
		'nothing',
		'notice',
		'noun',
		'now',
		'number',
		'numeral',
		'object',
		'observe',
		'ocean',
		'of',
		'off',
		'office',
		'often',
		'oh',
		'oil',
		'old',
		'on',
		'once',
		'one',
		'only',
		'open',
		'opposite',
		'or',
		'order',
		'other',
		'our',
		'out',
		'outside',
		'over',
		'own',
		'oxygen',
		'page',
		'paint',
		'pair',
		'paper',
		'paragraph',
		'park',
		'part',
		'particular',
		'party',
		'passed',
		'past',
		'pattern',
		'pay',
		'people',
		'per',
		'perhaps',
		'period',
		'person',
		'phrase',
		'picked',
		'picture',
		'piece',
		'place',
		'plains',
		'plan',
		'plane',
		'planets',
		'plant',
		'play',
		'please',
		'plural',
		'poem',
		'point',
		'pole',
		'poor',
		'position',
		'possible',
		'pounds',
		'power',
		'practice',
		'prepared',
		'present',
		'president',
		'pretty',
		'printed',
		'probably',
		'problem',
		'process',
		'produce',
		'products',
		'property',
		'provide',
		'pulled',
		'pushed',
		'put',
		'questions',
		'quickly',
		'quiet',
		'quite',
		'race',
		'radio',
		'rain',
		'raised',
		'ran',
		'rather',
		'reached',
		'read',
		'ready',
		'real',
		'reason',
		'received',
		'record',
		'red',
		'region',
		'remain',
		'remember',
		'repeated',
		'report',
		'represent',
		'rest',
		'result',
		'return',
		'rhythm',
		'rich',
		'ride',
		'right',
		'ring',
		'rise',
		'river',
		'road',
		'rock',
		'rolled',
		'room',
		'root',
		'rope',
		'rose',
		'round',
		'row',
		'rule',
		'run',
		'safe',
		'said',
		'sail',
		'same',
		'sand',
		'sat',
		'save',
		'saw',
		'say',
		'scale',
		'school',
		'science',
		'scientists',
		'score',
		'sea',
		'seat',
		'second',
		'section',
		'see',
		'seeds',
		'seem',
		'seen',
		'sell',
		'send',
		'sense',
		'sent',
		'sentence',
		'separate',
		'serve',
		'set',
		'settled',
		'seven',
		'several',
		'shall',
		'shape',
		'sharp',
		'she',
		'ship',
		'shoes',
		'shop',
		'short',
		'should',
		'shoulder',
		'shouted',
		'show',
		'shown',
		'side',
		'sight',
		'sign',
		'silent',
		'similar',
		'simple',
		'since',
		'sing',
		'single',
		'sir',
		'sister',
		'sit',
		'site',
		'six',
		'size',
		'skin',
		'sky',
		'sleep',
		'slowly',
		'small',
		'smell',
		'smiled',
		'snow',
		'so',
		'soft',
		'soil',
		'soldiers',
		'solution',
		'solve',
		'some',
		'someone',
		'something',
		'sometimes',
		'son',
		'song',
		'soon',
		'sound',
		'south',
		'southern',
		'space',
		'speak',
		'special',
		'speed',
		'spell',
		'spot',
		'spread',
		'spring',
		'square',
		'stand',
		'stars',
		'start',
		'state',
		'statement',
		'stay',
		'steel',
		'step',
		'stick',
		'still',
		'stone',
		'stood',
		'stop',
		'store',
		'story',
		'straight',
		'strange',
		'stream',
		'street',
		'stretched',
		'string',
		'strong',
		'students',
		'study',
		'subject',
		'substances',
		'such',
		'suddenly',
		'suffix',
		'sugar',
		'suggested',
		'sum',
		'summer',
		'sun',
		'supply',
		'suppose',
		'sure',
		'surface',
		'surprise',
		'swim',
		'syllables',
		'symbols',
		'system',
		'table',
		'take',
		'talk',
		'tall',
		'teacher',
		'team',
		'tell',
		'temperature',
		'ten',
		'terms',
		'test',
		'than',
		'that',
		'the',
		'their',
		'them',
		'themselves',
		'then',
		'there',
		'these',
		'they',
		'thick',
		'thin',
		'things',
		'think',
		'third',
		'this',
		'those',
		'though',
		'thought',
		'thousands',
		'three',
		'through',
		'thus',
		'tied',
		'time',
		'tiny',
		'to',
		'today',
		'together',
		'told',
		'tone',
		'too',
		'took',
		'tools',
		'top',
		'total',
		'touch',
		'toward',
		'town',
		'track',
		'trade',
		'train',
		'travel',
		'tree',
		'triangle',
		'trip',
		'trouble',
		'truck',
		'true',
		'try',
		'tube',
		'turn',
		'two',
		'type',
		'uncle',
		'under',
		'underline',
		'understand',
		'unit',
		'until',
		'up',
		'upon',
		'us',
		'use',
		'usually',
		'valley',
		'value',
		'various',
		'verb',
		'very',
		'view',
		'village',
		'visit',
		'voice',
		'vowel',
		'wait',
		'walk',
		'wall',
		'want',
		'war',
		'warm',
		'was',
		'wash',
		'Washington',
		'wasn’t',
		'watch',
		'water',
		'waves',
		'way',
		'we',
		'wear',
		'weather',
		'week',
		'weight',
		'we’ll',
		'well',
		'went',
		'were',
		'west',
		'western',
		'what',
		'wheels',
		'when',
		'where',
		'whether',
		'which',
		'while',
		'white',
		'who',
		'whole',
		'whose',
		'why',
		'wide',
		'wife',
		'wild',
		'will',
		'win',
		'wind',
		'window',
		'wings',
		'winter',
		'wire',
		'wish',
		'with',
		'within',
		'without',
		'woman',
		'women',
		'wonder',
		'won’t',
		'wood',
		'words',
		'work',
		'workers',
		'world',
		'would',
		'wouldn’t',
		'write',
		'written',
		'wrong',
		'wrote',
		'yard',
		'years',
		'yellow',
		'yes',
		'yet',
		'you',
		'young',
		'your',
		'you’re',
		'yourself'
	]; // Array of words
	let currentWords = Array(9).fill(''); // Array to hold current words for each mole

	function changeRandomLetter(word) {
		const randomIndex = Math.floor(Math.random() * word.length);
		const randomChar = String.fromCharCode(Math.floor(Math.random() * 26) + 97); // Generate a random lowercase letter
		return word.substring(0, randomIndex) + randomChar + word.substring(randomIndex + 1);
	}

	function startGame() {
		score = 0;
		gameActive = true;
		currentWords = Array(9).fill(''); // Reset current words
		moleTimer();
	}

	function moleTimer() {
		if (!gameActive) return;
		const randomIndex = Math.floor(Math.random() * moles.length);
		moles[randomIndex] = true;
		const originalWord = words[Math.floor(Math.random() * words.length)];
		currentWords[randomIndex] = originalWord; // Assign a random word

		const secondIndex = Math.floor(Math.random() * moles.length);
		moles[secondIndex] = true;
		currentWords[secondIndex] = changeRandomLetter(originalWord); // Use the same word with one letter changed

		setTimeout(() => {
			moles[randomIndex] = false;
			currentWords[randomIndex] = ''; // Clear the word when mole disappears
			moles[secondIndex] = false; // Hide the second mole
			currentWords[secondIndex] = ''; // Clear the word for the second mole
			moleTimer();
		}, 3000); // Both moles appear for 3 seconds
	}

	function whack(index) {
		if (moles[index]) {
			const wordClicked = currentWords[index]; // Store the word of the clicked mole
			if (words.includes(wordClicked)) {
				// Check if the clicked word is in the words array
				score++; // Increase score only if the word is valid
				clickedWord = '✅ ' + wordClicked; // Update clickedWord with check emoji
				clickedWordList.push(wordClicked); // Append valid word to clickedWordList
				console.log(clickedWordList); // Log the clickedWordList to the console
				showCheckEmoji = true; // Show check emoji if the word is valid

				// Hide the check emoji after 0.5 seconds
				setTimeout(() => {
					showCheckEmoji = false;
				}, 500);
			} else {
				clickedWord = '❌ ' + wordClicked; // Add X emoji for invalid word
				showXEmoji = true; // Show X emoji if the word is invalid

				// Hide the X emoji after 1 second
				setTimeout(() => {
					showXEmoji = false;
				}, 1000);
			}
			moles[index] = false; // Hide the mole after whacking
			currentWords[index] = ''; // Clear the word when whacked
		}
	}

	function endGame() {
		gameActive = false;
		alert(`Game Over! Your score: ${score}`);
	}
</script>

<h1>Whack-a-Mole Game</h1>
<button on:click={startGame}>Start Game</button>
<button on:click={endGame}>End Game</button>
<div class="grid">
	{#each moles as mole, index}
		<div class="mole {mole ? 'active' : ''}" on:click={() => whack(index)}>
			<img src="/assets_whack/mole.png" alt="Mole" />
			{#if mole}
				<span class="word">{currentWords[index]}</span>
			{/if}
		</div>
	{/each}
</div>
<p>Score: {score}</p>
<div class="clicked-word">Clicked Word: {clickedWord}</div>
{#if showCheckEmoji}
	<div class="check-emoji">✅</div>
	<!-- Display check emoji -->
{/if}
{#if showXEmoji}
	<div class="x-emoji">❌</div>
	<!-- Display X emoji -->
{/if}

<!-- Output clicked words as a simple paragraph -->
<p class="clicked-word-list">
	Valid Clicked Words: {clickedWordList.join(', ')}
</p>

<style>
	.grid {
		margin-top: 30px;
		padding: 20px;
		display: grid;
		grid-template-columns: repeat(3, 100px);
		grid-gap: 40px;
		justify-content: center;
		background-color: rgb(215, 215, 215);
	}
	.mole {
		width: 100px;
		height: 100px;
		background-color: brown;
		border-radius: 50%;
		display: flex;
		justify-content: center;
		align-items: center;
		cursor: pointer;
		position: relative;
		overflow: hidden;
	}
	.mole img {
		width: 80%;
		height: auto;
		position: absolute;
		bottom: -100%;
		left: 10%;
		animation: rise 0.5s forwards;
		display: none;
	}
	.mole.active img {
		display: block;
		animation: rise 0.5s forwards;
	}
	.mole .word {
		position: absolute;
		top: 10%; /* Adjust as needed */
		left: 50%;
		transform: translateX(-50%);
		color: white; /* Change color as needed */
		font-weight: bold;
		font-size: 20px; /* Adjust font size as needed */
		z-index: 1; /* Ensure the word is on top */
	}
	.clicked-word {
		margin-top: 20px; /* Add some spacing */
		font-size: 18px; /* Adjust font size as needed */
		color: black; /* Change color as needed */
	}
	.check-emoji {
		position: fixed;
		top: 50%;
		left: 50%;
		transform: translate(150%, -140%);
		font-size: 100px; /* Adjust size as needed */
		color: green; /* Change color as needed */
		z-index: 10; /* Ensure it appears above other elements */
	}
	.x-emoji {
		position: fixed;
		top: 50%;
		left: 50%;
		transform: translate(-50%, -50%);
		font-size: 100px; /* Adjust size as needed */
		color: red; /* Change color as needed */
		z-index: 10; /* Ensure it appears above other elements */
	}

	@keyframes rise {
		from {
			bottom: -200%;
		}
		to {
			bottom: -20%;
		}
	}

	.clicked-word-list {
		margin-top: 20px; /* Add some spacing */
		font-size: 16px; /* Adjust font size as needed */
		color: black; /* Change color as needed */
	}
</style>
